### ISSUE TITLE
[QA] Failing unit tests for v9.0.11 both on postgres and mysql

### ISSUE THREAD

**Issue by saw-jan** [owncloud/update-testing#48]
Build: https://drone.owncloud.com/owncloud/update-testing/2195/5/6
```php
There were 2 failures:

1) Test\Files\Config\UserMountCacheTest::testGetMountsForFileIdRootId
Failed asserting that actual size 0 matches expected size 1.

/drone/src/owncloud/tests/lib/Files/Config/UserMountCacheTest.php:358

2) Test\Files\Config\UserMountCacheTest::testGetMountsForFileIdSubFolder
Failed asserting that actual size 0 matches expected size 1.

/drone/src/owncloud/tests/lib/Files/Config/UserMountCacheTest.php:380
```

**Comment by PrajwolAmatya** [comment]
These failures started to occur from Sept 20. https://github.com/owncloud/core/pull/40959 this PR was merged before the failure started to occur. Maybe we need to look into it.
CC @phil-davis @DeepDiver1975

**Comment by phil-davis** [comment]
Seems to have started with https://drone.owncloud.com/owncloud/update-testing/2189/4/6 on Sep 20, 2023, 5:45 AM

And https://github.com/owncloud/core/pull/40959 was merged Sep 19, 2023. So I suppose something in that has caused this change when running the unit tests after having done an upgrade from a 9.0.11 system. But there are 3 pipelines that run for testing upgrades from 9.0.11 - the mysql and pgsql pipelines have this failures. But the Oracle pipeline passes - it's strange that the test works on Oracle database.

**Comment by phil-davis** [comment]
It all passes for upgrades from 8.2.11 or 9.1.8 or 10.*

The "special" thing about 9.0.11 is that it is not the last minor release of major version 9.

**Comment by phil-davis** [comment]
See #50 - upgrade from 9.0 to 9.1, then to 10.0, gets the unit tests passing.
